spring:
  application:
    name: board
  # DataSource Configuration
  datasource:
    url: jdbc:postgresql://127.0.0.1:5432/board
    username: test
    password: 1234
    hikari:
      auto-commit: false
  jpa:
    hibernate:
      ddl-auto: create
  devtools:
    restart:
      enabled: true
  mvc:
    static-path-pattern: /**
  servlet:
    multipart:
      max-file-size: 10MB
server:
  port: 8080
logging:
  level:
    org.springframework.web: info

cors:
  allowed-methods:
    - GET
    - POST
    - PUT
    - DELETE
    - PATCH
  allowed-origins:
    - http://localhost:3000

jwt:
  authorize-header: Authorization
  authorize-key: auth
  bearer-type: Bearer
  # mili-seconds: 60 * 30 * 1000
  token-expire-time: 1800000
  secret-key: GGNepulWYYV92qf3OQtwKh2TZLtVaE1a6NARvsSn53II41QC6tEAnJZgU7UAM1rAlLUvOVvcoArTlMvpzBhllw==
